# 错误处理

当错误发生时，SDK使用异常来高亮显示它们，SDK所定义的异常类型亦是python解释器所定义，所有的异常定义可以从
*ovirtsdk.infrastructer.errors*模块中找到。

*ConnectionError*.  
当传输层发生错误时抛出。

*DisconnectedError*.  
当已经明确的断开连接后尝试使用SDK时会抛出。

*ImmutableError*.  
当初始化SDK时，此SDK的实例在相同的域下已经存在，这个时候会抛出此异常。

*NoCertificatesError*.  
没有CA证书时抛出，当然insecure设置为False。

*RequestError*.  
任何类型的oVirt服务端错误发生时抛出。

*UnsecuredConnectionAttemptError*.  
当服务端使用的是HTTPS协议，而尝试使用HTTP协议连接时抛出。

*MissingParametersError*.  
当使用get()方法时没有提供或id或名称的任何参数时抛出。

上述这些异常在捕获和处理时和python的异常一样。

    from ovirtsdk.api import API
    from ovirtsdk.xml import params
    try:
         api = API(url="https://HOST",
                   user="USER,
                   pass="PASS,
                   ca_file="/etc/pki/ovirt-engine/ca.pem")
    except ConnectionError, err:
        print "Connection failed: %s" % err
                     

